databases:
  staging:
    url: <%= ENV["PGHERO_DATABASE_URL"] %>
  production:
    url: <%= ENV["HEROKU_POSTGRESQL_CHARCOAL_URL"] %>
  production_follower:
    url: <%= ENV["HEROKU_POSTGRESQL_WHITE_URL"] %>